# Generated by Django 5.0.6 on 2025-08-18 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the data source', max_length=100, unique=True)),
                ('url', models.URLField(blank=True, help_text='URL of the data source (for API or file downloads)', null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the data source')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this data source is currently active')),
                ('last_fetch', models.DateTimeField(blank=True, help_text='Last time data was fetched from this source', null=True)),
                ('fetch_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('manual', 'Manual')], default='weekly', help_text='How often to fetch data from this source', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField(help_text='Week number in the year (1-52)')),
                ('year', models.PositiveIntegerField(default=2025, help_text='Year of the data')),
                ('month', models.CharField(help_text='Month name (e.g., January, February)', max_length=20)),
                ('rainfall_mm', models.DecimalField(decimal_places=2, help_text='Rainfall in millimeters', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('temperature_c', models.DecimalField(decimal_places=2, help_text='Temperature in Celsius', max_digits=5)),
                ('market_day', models.BooleanField(default=False, help_text="Whether it's a market day (yes/no)")),
                ('school_open', models.BooleanField(default=True, help_text='Whether schools are open (yes/no)')),
                ('disease_alert', models.CharField(choices=[('Presence', 'Disease Present'), ('Absence', 'No Disease')], default='Absence', help_text='Disease alert status', max_length=20)),
                ('last_week_demand', models.CharField(choices=[('Low', 'Low Demand'), ('Medium', 'Medium Demand'), ('High', 'High Demand')], help_text="Previous week's demand level", max_length=20)),
                ('market_demand', models.CharField(choices=[('Low', 'Low Demand'), ('Medium', 'Medium Demand'), ('High', 'High Demand')], help_text='Current market demand level', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default='manual_upload', help_text='Data source (e.g., manual_upload, github_fetch)', max_length=100)),
            ],
            options={
                'verbose_name': 'Market Data',
                'verbose_name_plural': 'Market Data',
                'ordering': ['-year', '-week'],
                'unique_together': {('year', 'week')},
            },
        ),
    ]
