# Generated by Django 5.0.6 on 2025-08-19 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='marketdata',
            options={'ordering': ['-year', '-week']},
        ),
        migrations.AlterField(
            model_name='datasource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='fetch_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('manual', 'Manual')], default='weekly', max_length=20),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='last_fetch',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='disease_alert',
            field=models.CharField(choices=[('Presence', 'Disease Present'), ('Absence', 'No Disease')], default='Absence', max_length=20),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='last_week_demand',
            field=models.CharField(choices=[('Low', 'Low Demand'), ('Medium', 'Medium Demand'), ('High', 'High Demand')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='market_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='market_demand',
            field=models.CharField(choices=[('Low', 'Low Demand'), ('Medium', 'Medium Demand'), ('High', 'High Demand')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='month',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='rainfall_mm',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='school_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='source',
            field=models.CharField(default='manual_upload', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='temperature_c',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='week',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
